### ISSUE TITLE
Url parameter setting

### ISSUE THREAD

**Issue by ggomabbang** [elon-kim/whenidie#5]
send parameter from index page to answer page and print simply that parameter at answer page

**Comment by elon-kim** [comment]
안되는디???? 결과확인 눌러도 그냥 https://elon-kim.github.io/whenidie/answer.html욜로가는디 왜지?!

**Comment by ggomabbang** [comment]
answer.html 뒤에 파라미터 아무것도 안 뜸? 뭐지 난 되는데

**Comment by elon-kim** [comment]
오 되네 이거 머지하고 바로 적용이 안되나봐
이열 멋있당 좀 치네 재선?
